import {useTranslation} from 'react-i18next';
import { Link } from 'react-router-dom';
import { ArrowLeft, BadgeCheck, LockKeyhole } from 'lucide-react';
import { money } from '../../utils/format';

export default function CheckoutSummarySection({ items, pricing }: { items: any[]; pricing: any }) {
  const {t}=useTranslation();
  return <aside className="lg:sticky lg:top-28 h-fit border thin-border bg-[#f7f3ed] p-5 md:p-7">
    <div className="flex items-start justify-between gap-4 pb-5 border-b thin-border"><div><p className="text-[10px] uppercase tracking-[.2em] text-muted">{t('checkout.yourOrder')}</p><h2 className="serif text-2xl mt-2">{t('checkout.summary')}</h2></div><span className="text-[10px] uppercase tracking-[.16em] text-muted">{items.reduce((n: number, item: any) => n + Number(item.quantity || 0), 0)} items</span></div>
    <div className="mt-6 space-y-5 max-h-[390px] overflow-auto pr-1 no-scrollbar">{items.map((item: any) => <div key={item.variantId} className="flex gap-4"><div className="relative w-20 h-24 bg-[#e5ded4] shrink-0 overflow-hidden"><img src={item.imageUrl || item.image} alt={item.productTitle || item.name || t('common.product')} className="w-full h-full object-cover"/><span className="absolute top-1 right-1 min-w-6 h-6 px-1 bg-ink text-white text-[9px] grid place-items-center rounded-full">{item.quantity}</span></div><div className="min-w-0 flex-1"><p className="text-sm font-medium leading-5">{item.productTitle || item.name}</p><p className="text-xs text-muted mt-1">{t('common.color')}: {item.color || 'Sand'}{item.size ? ` · ${t('common.size')} ${item.size}` : ''}</p><p className="text-sm mt-3">{money(item.finalLineTotal ?? (item.unitPrice || 0) * item.quantity, 'EGP')}</p></div></div>)}</div>
    <div className="border-t thin-border mt-6 pt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><span>{t('common.subtotal')}</span><span>{money(pricing.effectiveSubtotal ?? 0, 'EGP')}</span></div>{pricing.totalLineDiscounts > 0 && <div className="flex justify-between gap-4"><span>{t('common.itemSavings')}</span><span>-{money(pricing.totalLineDiscounts, 'EGP')}</span></div>}<div className="flex justify-between gap-4"><span>{t('common.shipping')}</span><span>{pricing.shippingFee > 0 ? money(pricing.shippingFee, 'EGP') : t('common.calculated')}</span></div>{pricing.totalDiscount > 0 && <div className="flex justify-between gap-4"><span>{t('common.discount')}</span><span>-{money(pricing.totalDiscount, 'EGP')}</span></div>}<div className="border-t thin-border pt-4 mt-4 flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-muted">{t('common.total')}</p><p className="serif text-3xl mt-1">{money(pricing.finalTotal ?? 0, 'EGP')}</p></div><span className="text-[10px] uppercase tracking-[.14em] text-muted">EGP</span></div></div>
    <div className="mt-6 p-4 bg-white/75 border border-black/5 flex items-start gap-3 text-xs leading-5 text-muted"><BadgeCheck size={16} className="mt-0.5 shrink-0 text-ink"/><span>{t('checkout.carried')}</span></div><div className="mt-4 flex items-center justify-center gap-2 text-[10px] uppercase tracking-[.14em] text-muted"><LockKeyhole size={13}/> {t('common.secureCheckout')}</div><Link to="/cart" className="inline-flex items-center gap-2 mt-6 text-[10px] uppercase tracking-[.17em] hover:opacity-60 transition-opacity"><ArrowLeft size={13}/> {t('common.editBag')}</Link>
  </aside>;
}
