import {useTranslation} from 'react-i18next';
import {Link} from 'react-router-dom';
import CartItem from './CartItem';
import {money} from '../../../utils/format';
export default function CartContentSection({loading,items,pricing,onChange,onRemove}:{loading:boolean;items:any[];pricing:any;onChange:(id:string,q:number)=>void;onRemove:(id:string)=>void}){const {t}=useTranslation();
 if(loading) return <section className="w-full px-5 md:px-8 pb-20"><div className="py-20 text-center text-muted">{t('cart.loading')}</div></section>;
 if(!items.length) return <section className="w-full px-5 md:px-8 pb-20"><div className="py-20 border-y thin-border text-center"><div className="serif text-3xl">{t('cart.empty')}</div><p className="text-sm text-muted mt-3">{t('cart.emptyText')}</p><Link to="/shop" className="inline-flex mt-8 h-12 px-6 bg-ink text-white items-center text-xs uppercase tracking-[.15em]">{t('common.continueShopping')}</Link></div></section>;
 return <section className="w-full px-5 md:px-8 pb-20"><div className="grid lg:grid-cols-[1fr_380px] gap-12"><div>{items.map((item:any)=><CartItem key={item.variantId} item={item} onChange={qty=>onChange(item.variantId,qty)} onRemove={()=>onRemove(item.variantId)}/>)}</div><aside className="bg-[#eee8df] p-7 h-fit"><h2 className="serif text-2xl">{t('cart.summary')}</h2><div className="mt-7 grid gap-4 text-sm"><div className="flex justify-between"><span>{t('common.subtotal')}</span><span>{money(pricing.effectiveSubtotal,'EGP')}</span></div>{pricing.totalLineDiscounts>0&&<div className="flex justify-between"><span>{t('common.itemSavings')}</span><span>-{money(pricing.totalLineDiscounts,'EGP')}</span></div>}<div className="flex justify-between"><span>{t('common.shipping')}</span><span>{money(pricing.shippingFee,'EGP')}</span></div>{pricing.totalDiscount>0&&<div className="flex justify-between"><span>{t('common.discount')}</span><span>-{money(pricing.totalDiscount,'EGP')}</span></div>}<div className="border-t thin-border pt-4 mt-2 flex justify-between font-medium"><span>{t('common.total')}</span><span>{money(pricing.finalTotal,'EGP')}</span></div></div><Link to="/checkout" className="w-full h-12 bg-ink text-white mt-8 text-xs uppercase tracking-[.16em] inline-flex items-center justify-center hover:bg-black/80 transition">{t('cart.proceed')}</Link><p className="text-[10px] text-muted mt-4 leading-5">{t('cart.reviewText')}</p></aside></div></section>
}
